(define tax_rate 0.065)
(define (start_pos)
  (display "Scheme Point-of-Sale") (newline)
  (display "Start transaction (exit with 0): ") (newline) (newline)
  (pos -1 0)  
  )

(define (pos value subtotal)
  (cond
	((= value 0) 
	 (newline) (display "Subtotal: $") (display subtotal) (newline)
	 (display "Tax: $") (display (* tax_rate subtotal)) (newline)
	 (display "Total: $") (display (* (+ tax_rate 1) subtotal))
	 #t)
	(else
	  (display "Enter value: ")
	  (let ((v (read))) (pos v (+ subtotal v))
		)
	  #t)
	)
  )
